language: python

dist: xenial
sudo: true

notifications:
  email: false

env:
  global:
    - PY_VENV=$TRAVIS_BUILD_DIR/venv
    - PYTHON=$PY_VENV/bin/python

matrix:
  include:
  - python: "3.6"
    dist: trusty
  - python: "3.6"
  - python: "3.7"

install:
  - python -m venv $PY_VENV
  - $PYTHON -m pip install -U pip wheel setuptools numpy
  - $PYTHON -m pip install -r requirements.txt

before_script:
  - $PYTHON setup.py install

script:
  - cd /tmp
  - $PYTHON -m pickle5.test.test_picklebuffer -v
  - $PYTHON -m pickle5.test.test_pickle
