os: linux
dist: xenial
language: python

notifications:
  email: false

env:
  global:
    - INSTALL_NUMPY=1
    - PY_VENV=$TRAVIS_BUILD_DIR/venv
    - PYTHON=$PY_VENV/bin/python

jobs:
  include:
  - python: "3.6"
    dist: trusty
    arch: amd64
  - python: "3.6"
    arch: amd64
  - python: "3.7"
    arch: amd64
  - python: "3.6"
    dist: bionic
    arch: arm64
  - python: "3.7"
    dist: bionic
    arch: arm64

install:
  - python -m venv $PY_VENV
  - export PIP="$PYTHON -m pip"
  # For some reason, pip caching fails on ARM64
  - export PIP_INSTALL="$PIP install --no-cache-dir"
  - $PIP_INSTALL -U pip wheel setuptools
  - |
    if [ "${INSTALL_NUMPY}" = "1" ]; then
      $PIP_INSTALL -U numpy
    fi
  - $PIP_INSTALL -r requirements.txt

before_script:
  - $PYTHON setup.py install

script:
  - cd /tmp
  - $PYTHON -m pickle5.test.test_picklebuffer -v
  - $PYTHON -m pickle5.test.test_pickle
